version: '2.1'
services:
    postgres:
        image: postgres:15.0
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          #- ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./user/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        healthcheck:
          test: ["CMD-SHELL", "pg_isready"]
          interval: 10s
          timeout: 5s
          retries: 5

    user:
      image: pozelim/product-review-app/user
      build:
        context: ./user
        dockerfile: Dockerfile
      depends_on:
        postgres:
          condition: service_healthy
      ports:
        - '8080:8080'